### ISSUE TITLE
port code to use clap and clap-derive or docopt

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/borrow-check#2]
Right now we don't support command-line arguments:

https://github.com/rust-lang-nursery/borrow-check/blob/8ef88dbe968db92dd9dfa0c0296c3c4a57608e0d/src/cli.rs#L9-L11

I'd like to add clap (with clap-derive) or docopt. Then we can have some command-line options. 

cc @killercup -- what's the "new hotness" in terms of super simple CLI wrappers? =)

**Comment by nikomatsakis** [comment]
As an example of some command-line options I would like:

The ability to *not* dump the resulting tuples and instead just see the time spent.

The ability to *not* see how much time is spent, perhaps?

The ability to dump *more* facts, for debugging, e.g. by passsing `true` instead of `false` here:

https://github.com/rust-lang-nursery/borrow-check/blob/8ef88dbe968db92dd9dfa0c0296c3c4a57608e0d/src/cli.rs#L17

**Comment by killercup** [comment]
@nikomatsakis I'm a super huge fan of [structopt](https://docs.rs/structopt/0.2.8/structopt/) -- a custom derive wrapper that writes clap invocations and parsing inputs to correct types for you. It'd look something like this (untested):

```rust
#[derive(StructOpt)]
/// Run borrow check tester or whatever this crate does
struct Cli {
    /// Input files
    #[structopt(parse(from_os_str))]
    files: Vec<PathBuf>,
    /// Don't dump the resulting tuples for some reasong
    #[structopt(short = "skip-tuples")]
    skip_tuples: bool,
    /// Don't print how much time is spent
    #[structopt(short = "skip-timing")]
    skip_timing: bool,
    /// Pass multiple times to increase verbosity (e.g., `-vv` to enable info level logging)
    #[structopt(short = "v", parse(from_occurrences))]
    verbosity: u64,
}

fn main() {
    let args = Cli::from_args();
    // …
}
```

You can use the verbosity flag to init a logger ([like this](https://github.com/killercup/quicli/blob/5ec1b649a39e78d5ce4a86c83fa8b8e2e1a94264/src/main_macro.rs#L38-L49), or to implement the "dump more flags" feature like `timed(|| Output::compute(all_facts, args.verbosity > 1)) `.
